version: '3.8'

services:
  php:
    build: .
    volumes:
      - ./:/var/www/html:delegated
      - ./var:/var/www/html/var
      - ./public:/var/www/html/public
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"
    depends_on:
      - db

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: